run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gofmt
    - goimports
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gosec
    - gocritic
    - revive

linters-settings:
  staticcheck:
    go: "1.21"
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - ST1005  # エラーメッセージの大文字化チェックを無効化（日本語対応）

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - gocritic
